apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example

spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: ...
    #   port: 3000
    #   targetPort: 8000
  type: LoadBalancer