apiVersion: v1
kind: Service
metadata:
  name: tasks-service

spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tasks-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-api
          image: abdurrahimsheikh/kube-tasks-node:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://aws-eks-abir:3qLF9uA1P6nGzyNk@cluster0.qqjlikt.mongodb.net/users?retryWrites=true&w=majority&appName=Cluster0'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'