apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: abdurrahimsheikh/kube-data-demo:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://aws-eks-abir:3qLF9uA1P6nGzyNk@cluster0.qqjlikt.mongodb.net/users-db?retryWrites=true&w=majority&appName=Cluster0'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'
