apiVersion: v1
kind: PersistentVolume

metadata:
  name: host-pv

spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate