sudo: required

services:
  - docker

before_install:
  - docker build -t abir/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abir/react/test npm test -- --coverage

after_success:
  - docker build -t abir/multi-client ./client
  - docker build -t abir/multi-ngnix ./nginx
  - docker build -t abir/multi-server ./server
  - docker build -t abir/multi-worker ./worker

  #  i did not added any travis password but it works like below

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  -docker push  abir/multi-client
  -docker push  abir/multi-nginx
  -docker push  abir/multi-server
  -docker push  abir/multi-worker